#!/bin/bash

#if $XDG_CACHE_HOME is empty, use $HOME/.cache
if [ -z "$XDG_CACHE_HOME" ]; then
  echo "XDG_CACHE_HOME is empty, use .cache instead"
  XDG_CACHE_HOME="${HOME}/.cache"
fi

#$XDG_CACHE_HOME/thumbnails/
if [ ! -f "${XDG_CACHE_HOME}/thumbnails/normal" ]; then
  mkdir -p ${XDG_CACHE_HOME}/thumbnails/normal
fi

function GenerateThumbnailIcon {
  MD5SUM=$(echo -n "file://${APPIMAGE}" | md5sum | awk '{print $1}')
  TIMESTAMP=$(date +%s)
  convert "${APPDIR}/FitTraining.png" -set "Thumb::URI" "${APPIMAGE}" /tmp/tmp.png
  convert /tmp/tmp.png -set "Thumb::MTime" "$TIMESTAMP" /tmp/1.png
  if [ ! -f "$XDG_CACHE_HOME/thumbnails/normal/$MD5SUM.png" ]; then
    cp /tmp/1.png $XDG_CACHE_HOME/thumbnails/normal/$MD5SUM.png
  fi
  if [ ! -f "${HOME}/.thumbnails/normal/${MD5SUM}.png" ]; then
    cp /tmp/1.png ${HOME}/.thumbnails/normal/${MD5SUM}.png
  fi
  rm -rf /tmp/tmp.png
  rm -rf /tmp/1.png

  #echo "$(env)" > /home/gwerners/Desktop/AppImage/newImage/debug.log
}

GenerateThumbnailIcon

SELF=$(readlink -f "$0")
HERE=${SELF%/*}
export PATH="${HERE}/usr/bin/:${HERE}/usr/sbin/:${HERE}/usr/games/:${HERE}/bin/:${HERE}/sbin/${PATH:+:$PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib/:${HERE}/usr/lib/i386-linux-gnu/:${HERE}/usr/lib/x86_64-linux-gnu/:${HERE}/usr/lib32/:${HERE}/usr/lib64/:${HERE}/lib/:${HERE}/lib/i386-linux-gnu/:${HERE}/lib/x86_64-linux-gnu/:${HERE}/lib32/:${HERE}/lib64/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export PYTHONPATH="${HERE}/usr/share/pyshared/${PYTHONPATH:+:$PYTHONPATH}"
export XDG_DATA_DIRS="${HERE}/usr/share/${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
export PERLLIB="${HERE}/usr/share/perl5/:${HERE}/usr/lib/perl5/${PERLLIB:+:$PERLLIB}"
export GSETTINGS_SCHEMA_DIR="${HERE}/usr/share/glib-2.0/schemas/${GSETTINGS_SCHEMA_DIR:+:$GSETTINGS_SCHEMA_DIR}"
export QT_PLUGIN_PATH="${HERE}/usr/lib/qt4/plugins/:${HERE}/usr/lib/i386-linux-gnu/qt4/plugins/:${HERE}/usr/lib/x86_64-linux-gnu/qt4/plugins/:${HERE}/usr/lib32/qt4/plugins/:${HERE}/usr/lib64/qt4/plugins/:${HERE}/usr/lib/qt5/plugins/:${HERE}/usr/lib/i386-linux-gnu/qt5/plugins/:${HERE}/usr/lib/x86_64-linux-gnu/qt5/plugins/:${HERE}/usr/lib32/qt5/plugins/:${HERE}/usr/lib64/qt5/plugins/${QT_PLUGIN_PATH:+:$QT_PLUGIN_PATH}"
EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2 | cut -d " " -f 1)
exec "${EXEC}" "$@"
